/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.videogen.ui.internal.VideogenActivator;

public class VideoGenUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return VideogenActivator.getInstance().getInjector("org.xtext.example.mydsl.VideoGen");
	}

}
