/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui.contentassist;

import org.xtext.example.mydsl.ui.contentassist.AbstractVideoGenProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class VideoGenProposalProvider extends AbstractVideoGenProposalProvider {
}
