/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.videogen.ui.internal.VideogenActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VideoGenExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return VideogenActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return VideogenActivator.getInstance().getInjector(VideogenActivator.ORG_XTEXT_EXAMPLE_MYDSL_VIDEOGEN);
	}
	
}
