/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractVideoGenIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class VideoGenIdeModule extends AbstractVideoGenIdeModule {
}
