/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.VideoGenRuntimeModule;
import org.xtext.example.mydsl.VideoGenStandaloneSetup;
import org.xtext.example.mydsl.ide.VideoGenIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class VideoGenIdeSetup extends VideoGenStandaloneSetup {
  @Override
  public Injector createInjector() {
    VideoGenRuntimeModule _videoGenRuntimeModule = new VideoGenRuntimeModule();
    VideoGenIdeModule _videoGenIdeModule = new VideoGenIdeModule();
    return Guice.createInjector(Modules2.mixin(_videoGenRuntimeModule, _videoGenIdeModule));
  }
}
