/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.videoGen.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.videoGen.BlackWhiteFilter;
import org.xtext.example.mydsl.videoGen.VideoGenPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Black White Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BlackWhiteFilterImpl extends FilterImpl implements BlackWhiteFilter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BlackWhiteFilterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VideoGenPackage.Literals.BLACK_WHITE_FILTER;
  }

} //BlackWhiteFilterImpl
