/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.videoGen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Negate Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.videoGen.VideoGenPackage#getNegateFilter()
 * @model
 * @generated
 */
public interface NegateFilter extends Filter
{
} // NegateFilter
