/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.videoGen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Video Seq</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.videoGen.VideoGenPackage#getVideoSeq()
 * @model
 * @generated
 */
public interface VideoSeq extends Media
{
} // VideoSeq
